Repository jenkins-infra/plugin-site, pull requests merged in 2019-09, with the labels that each got.

#57 [INFRA-2229] - Enable Release Drafter in the repository
  .github/release-drafter.yml
Labels: chore

#58 Update the plugins number on the Plugin Site front page
  app/components/Main.jsx
Labels: enhancement

#59 Promote Plugin Site 1.6.0 to production
  .github/release-drafter.yml
  Jenkinsfile
  app/components/LineChart.jsx
  app/components/Main.jsx
  app/components/PluginDetail.jsx
Labels: skip-changelog

#61 Remove red `(required)` from mandatory dependencies
  app/components/PluginDetail.jsx
  public/assets/css/base.css
Labels: enhancement

#60 Use ≥ rather than v. notation in plugin version requirements
  app/components/PluginDetail.jsx
Labels: enhancement

#62 Add Changelog and Gitter badges to README
  README.md
Labels: documentation
