Repository jenkins-infra/plugin-site, pull requests merged in 2020-04, with the labels that each got.

#195 Add support for developers to enable a single plugin's content to speed up local development
  plugins/gatsby-source-jenkinsplugins/utils.js
Labels: skip-changelog

#194 Update all the dependancies
  package.json
  yarn.lock
Labels: dependencies

#199 Remove Jira table, improve side panel links
  plugins/gatsby-source-jenkinsplugins/utils.js
  src/styles/base.css
  src/templates/plugin.jsx
Labels: bug
