Repository jenkins-infra/plugin-site, pull requests merged in 2020-10, with the labels that each got.

#379 Show dependent pulgins in dependencies tab
  src/components/PluginDependencies.jsx
  src/styles/base.css
  src/templates/plugin.jsx
Labels: enhancement

#385 Replace react-time-ago with react-timeago
  package.json
  src/commons/helper.js
  src/components/PluginLastReleased.jsx
  src/components/PluginReleases.jsx
  src/templates/plugin.jsx
  utils.js
  yarn.lock
Labels: chore, enhancement

#399 Added plugin-release specific styling for release categories.
  src/components/PluginReleases.css
Labels: enhancement, hacktoberfest-accepted

#400 Search page - Single-column layout is broken on mobile
  src/components/SearchResults.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#403 Hacktoberfest - Generate favicons set from image with transparent
  gatsby-config.js
  src/images/android-chrome-512x512.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#386 Move alerts to top and update their styles
  .gitignore
  gatsby-config.js
  package.json
  src/components/PluginActiveWarnings.jsx
  src/components/PluginGovernanceStatus.jsx
  src/components/PluginInactiveWarnings.jsx
  src/images/warning.svg
  src/styles/base.css
  src/templates/plugin.jsx
  yarn.lock
Labels: enhancement, hacktoberfest-accepted

#402 #129 - Optimize scaling of plugin installation trends
  src/components/LineChart.jsx
Labels: enhancement, hacktoberfest-accepted

#444 Hacktoberfest: Remove the white strip below the navigation
  src/styles/base.css
  src/templates/search.jsx
  utils.js
Labels: bug

#446 infra.ci jenkinsfile fixes
  Jenkinsfile_k8s
  PodTemplates.yaml
Labels: chore, skip-changelog
