Repository jenkins-infra/plugin-site, pull requests merged in 2021-12, with the labels that each got.

#889 Fix Renovate's automerge config
  renovate.json
Labels: chore

#890 Switch plugin page tabs to real urls
  .eslintrc.js
  gatsby-node.js
  src/templates/plugin.jsx
Labels: bug, enhancement

#938 configure release drafter as github action instead of app
  .github/workflows/release-drafter.yml
Labels: chore

#939 Wrap plugin content tables in bootstrap classes
  plugins/gatsby-rehype-wrap-tables-bootstrap/.eslintrc.js
  plugins/gatsby-rehype-wrap-tables-bootstrap/__tests__/index.test.js
  plugins/gatsby-rehype-wrap-tables-bootstrap/babel.config.json
  plugins/gatsby-rehype-wrap-tables-bootstrap/gatsby-node.js
  plugins/gatsby-rehype-wrap-tables-bootstrap/index.js
  plugins/gatsby-rehype-wrap-tables-bootstrap/jest-global-setup.js
  plugins/gatsby-rehype-wrap-tables-bootstrap/package.json
  plugins/plugin-site/gatsby-config.js
  plugins/plugin-site/package.json
  plugins/plugin-site/src/styles/base.css
  yarn.lock
Labels: enhancement
